Fix : fix undefined parameter errors in github actions
cms-btv-pog/BTVNanoCommissioning pull request #26
Opened 2022-06-10 21:06 UTC by Ming-Yan

- Fix undefined parameter errors in github actions
- Add DeepJet binning info to `definitions.py`

2022-06-11 08:58 UTC, andrzejnovak requested changes
There are some straggling lines left over and please run black (https://github.com/psf/black) but otherwise LGTM

2022-06-11 09:05 UTC, Ming-Yan commented on src/BTVNanoCommissioning/workflows/__init__.py
> +<<<<<<< HEAD
fix

2022-06-11 09:06 UTC, Ming-Yan commented on README.md
> +<<<<<<< HEAD
fix

2022-06-11 09:19 UTC, andrzejnovak commented on README.md
> +```
These are wrong I think

2022-06-13 10:13 UTC, andrzejnovak approved these changes

2022-06-13 10:14 UTC, merged